language: node_js
node_js:
- node
- '20'
dist: xenial
script: yarn build
cache:
  yarn: true
notifications:
  webhooks:
    urls:
    - https://www.travisbuddy.com/
    on_success: never
    on_failure: always
    on_start: never
    on_cancel: never
    on_error: never
before_deploy:
  - cd dist
deploy:
  provider: npm
  email: aftermathinc@gmail.com
  skip_cleanup: true
  api_key:
    secure: U5BSRVzZvPm0lXZ8Hbjz8gq8jgg23HZ+xuhiC8imKTvoUvpL3WIAEvOeRLlnK3SUCuUIt+v77QLvCv6dstxbddqbgQ/M+6PNxBEibOscpz76z7wxnEUytb1n46NyzvXV5VSBB1mzhKPrxrN75aNXdDK1LnIVNT+NJ5d7+NFKCkgBFn1vsS/CB5LRymlH+r5elSHfiwFQpyAJKgmiJNqTSwJTAIaUY/ciDylLrlucoekmGe6v+KmrigHTNJH/07tnGRQYQhIW8Kp3nvpvd2thWMF4DDBZCOf3f0caf3Yz9Ur9/QyAnN5Y3T6vqS/Y8X+fEKETNIJ+9UJUkmzcBtP6vhFZ/VvyzyMEfdlYGs1dSJOIS+UZooHwsbZmmR/NaCTMrwWDh5bhLR6FuJckWltqtl4FMRfrt0I1L/pwUjHAElMcgsW9C5ZlFJzGFgjh4fWc9L1Agq6Cty1bvf6qdYI3I0/5SOrIFhla/suyICemhmpkVGk/SbngWSMfToXEXPoyANHtW8Krypx++AH8rqnUpnxVP7/5LefWJdDFLywP+5qRxfO1rmDChg388yZ6R8L1+60Gr+XyHh0VpumCstXbDzEz0KWH+2dG09zitMO24dImotOm0103TzQ/Yvh/iNHS7QXXCyUoDthlOb41OM+4Oldy0d3rUuXmOEOUvVPpohY=
  on:
    tags: true
    repo: Tgure/ngx-loggly-logger
